"""Constants for the UniFi Access API client."""

UNIFI_ACCESS_API_PORT = 12445
DOORS_URL = "/api/v1/developer/doors"
DOOR_UNLOCK_URL = "/api/v1/developer/doors/{door_id}/unlock"
DOOR_LOCK_RULE_URL = "/api/v1/developer/doors/{door_id}/lock_rule"
DEVICE_NOTIFICATIONS_URL = "/api/v1/developer/devices/notifications"
DEVICES_URL = "/api/v1/developer/devices"
DOORS_EMERGENCY_URL = "/api/v1/developer/doors/settings/emergency"
STATIC_URL = "/api/v1/developer/system/static"
PROTECT_META_INFO_URL = "/proxy/protect/integration/v1/meta/info"
USERS_URL = "/api/v1/developer/users"
USER_URL = "/api/v1/developer/users/{user_id}"
USER_PIN_CODES_URL = "/api/v1/developer/users/{user_id}/pin_codes"
DEVICE_SETTINGS_URL = "/api/v1/developer/devices/{device_id}/settings"
